name: Add Submodule

on:
  workflow_dispatch:  # Позволяет запускать вручную из интерфейса GitHub
    inputs:
      repo_url:
        description: 'URL чужого репозитория'
        required: true
        default: 'https://github.com/author/library.git'
      path:
        description: 'Путь для сохранения (например, libs/mylib)'
        required: true
        default: 'libs/mylib'

jobs:
  add-submodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Add submodule
        run: |
          git submodule add ${{ github.event.inputs.repo_url }} ${{ github.event.inputs.path }}
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add submodule ${{ github.event.inputs.repo_url }}"
          git push
